logflights/urls.py
from django.urls import include, path, re_path
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings
from django.views.generic import TemplateView
from planner import views, api_views, external_urls
from rest_framework_jwt.views import obtain_jwt_token
from rest_framework_swagger.views import get_swagger_view

urlpatterns = [
    # App routes
    path('accounts/', include('allauth.urls')),

    path('auth/api-token-auth/', obtain_jwt_token),

    # api docs
    path('api/docs', api_views.schema_view),
    re_path(r'_/docs/?', get_swagger_view(title='log.flights API')),

    # Administrative routes to be protected by http proxy / load balancer
    re_path(r'_/admin/?', admin.site.urls),
    re_path(r'_/health_check/?', views.HealthCheckView.as_view(), name='health_check'),
    path('api/internal/', include('planner.api_urls', namespace='planner_api')),
    path('api/experimental/', include('planner.external_urls', namespace='export_api')),
    path('', TemplateView.as_view(template_name='react/index.html'), name="welcome"),
    # match all other routes
    re_path(r'^(?:.*)/?$', TemplateView.as_view(template_name='react/index.html'), name="welcome"),

    # old ui

    # url(r'^$', views.welcome, name='welcome'),
    # url(r'^planner/', include('planner.urls', namespace='planner')),
    # url(r'^accounts/', include('allauth.urls')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

planner/urls.py
from django.conf.urls import url

from . import views

app_name = 'planner'

urlpatterns = [
    url(r'^vehicle/$', views.vehicle, name="vehicle"),
    url(r'^create-vehicle/$', views.create_vehicle, name="create_vehicle"),
    url(r'^update-vehicle/(?P<id>[0-9a-z]+)/$', views.update_vehicle, name="update_vehicle"),
    url(r'^terms/$', views.terms, name="terms"),

    url(r'^flightplan/$', views.flightplan, name="flightplan"),
    url(r'^create-flight-plan/$', views.create_flight_plan, name="create_flight_plan"),
    url(r'^update-flight-plan/(?P<id>[0-9a-z]+)/$', views.update_flight_plan, name="update_flight_plan"),
    url(r'^invalidate-flight-plan/(?P<id>[0-9a-z]+)/$', views.invalidate_flight_plan, name="invalidate_flight_plan"),
    url(r'^detail-flight-plan/(?P<id>[0-9a-z]+)/$', views.detail_flight_plan, name="detail_flight_plan"),

    url(r'^get-upload-url$', views.get_upload_url, name="get_upload_url"),
    url(r'^set-upload-complete$', views.set_upload_complete, name="set_upload_complete"),
    url(r'^get-upload-state/(?P<type>[a-z]+)/(?P<id>[0-9a-z]+)$', views.get_upload_state, name="get_upload_state"),
    url(r'^flightplans/(?P<id>[0-9a-z]+)/telemetry/$', views.download_telemetry, name="download_telemetry"),
    url(r'^get-flight-plan-data/(?P<id>[0-9a-z]+)/$', views.get_flight_plan_data, name="get_flight_plan_data"),
    url(r'^search-flights/$', views.search_flights, name= "search_flights"),
    url(r'^profile/$', views.edit_profile, name="edit_profile"),
    url(r'^change-password/$', views.change_password, name="change_password"),
]

planner/forms.py
from django import forms
from .models import Operator, Vehicle, FlightPlan, Manufacturer
from django.conf import settings
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.core.validators import RegexValidator
from django.db.models import Case, Value, When
from django.db.models.functions import Lower
from django.forms import ModelChoiceField

class SignupForm(forms.ModelForm):
    first_name = forms.CharField(max_length=100)
    last_name = forms.CharField(max_length=100)

    class Meta:
        model = Operator
        fields = (
            'organization',
            'mobile_number'
        )

    def signup(self, request, user):
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.save()

        Operator.objects.create(
            user = user,
            organization = self.cleaned_data['organization'],
            mobile_number = self.cleaned_data['mobile_number']
        )

class VehicleForm(forms.ModelForm):
    manufacturer = ModelChoiceField(
        # sort the first key, which is "Other" to the beginning of the list
        queryset=Manufacturer.objects.order_by(Case(When(id__exact=0, then=Value('00000')), default=Lower('name'))),
        empty_label=None,
        initial=0,
    )
    class Meta:
        model = Vehicle
        fields = (
            'model',
            'serial_number',
            'vehicle_type',
            'empty_weight',
            'manufacturer',
            'state'
        )

class FlightPlanForm(forms.ModelForm):
    wm_id = forms.CharField(label="Flight plan", required=False)

    def __init__(self,user,*args,**kwargs):
        super(FlightPlanForm,self).__init__(*args,**kwargs)
        operator = Operator.objects.filter(user=user).first()
        if operator:
            self.fields['vehicle'].queryset = Vehicle.objects.filter(operator=user.operator, state=Vehicle.STATE_ACTIVE)

    class Meta:
        model = FlightPlan
        fields = (
            'flight_id',
            'wm_id',
            'planned_departure_time',
            'planned_arrival_time',
            'payload_weight',
            'vehicle',
            'mission_type'
        )

class EditProfileForm(forms.ModelForm):
    organization = forms.CharField(required=True)
    mobile_number = forms.CharField(required=True)

    class Meta:
        model = User
        fields = (
            'first_name',
            'last_name',
            'email',
            'organization',
            'mobile_number'
        )

    def __init__(self, *args, **kwargs):
        super(EditProfileForm, self).__init__(*args, **kwargs)

        self.fields['first_name'].required = True
        self.fields['last_name'].required = True

    def save(self):
        super(EditProfileForm,self).save()
        operator = self.instance.operator
        operator.organization = self.cleaned_data['organization']
        operator.mobile_number = self.cleaned_data['mobile_number']
        operator.save()

class ChangePasswordForm(forms.ModelForm):
    oldpassword = forms.CharField(required=True)
    password1 = forms.CharField(required=True)
    password2 = forms.CharField(required=True)

    class Meta:
        model = User
        fields = (
            'oldpassword',
            'password1',
            'password2'
        )

    def clean_oldpassword(self):
        if not self.instance.check_password(self.cleaned_data.get("oldpassword")):
            raise forms.ValidationError("Please type your current password.")
        return self.cleaned_data["oldpassword"]

    def clean(self):
        if not (self.cleaned_data.get("password1") == self.cleaned_data.get("password2")):
            raise forms.ValidationError("Password1 and Password2 must match.")
        return self.cleaned_data

    def save(self):
        user = self.instance
        user.set_password(self.cleaned_data["password1"])
        user.save()

planner/views.py
# -*- coding: utf-8 -*-
from datetime import datetime
from datetime import time
import os
from pytz import UTC

from django.template import loader
from django.core import serializers
from django.core.files.storage import default_storage
from django.urls import reverse
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.db.models import F, Q, Count, FloatField
from django.db.models.functions import Cast
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse, Http404
from django.shortcuts import render, redirect
from django.utils import dateparse
from django.views.decorators.csrf import csrf_exempt

from health_check.views import MainView
from .tasks import process_waypoints, process_telemetry

from .models import Operator, Manufacturer, Vehicle, MissionType, FlightPlan, \
    Waypoint, WaypointMetadata, TelemetryMetadata, \
    document_path
from .forms import VehicleForm, FlightPlanForm, EditProfileForm, ChangePasswordForm

def welcome(request):
    # Only show operators that have at least 1 planned flight
    operators = Operator.objects.annotate(num_flights=Count('flightplan')).filter(num_flights__gt=0, is_test=False)
    flightplans = FlightPlan.objects.filter(
        Q(state=FlightPlan.STATE_PLANNED) | Q(state=FlightPlan.STATE_COMPLETED),
        operator__is_test=False
    ).order_by('-planned_departure_time')
    return render(request, 'planner/welcome.html',{'operators': operators, 'flightplans': flightplans})

@login_required
def vehicle(request):
    if request.user.operator:
        vehicle_query = Vehicle.objects.filter(operator=request.user.operator).order_by('-created_at')
        active_vehicles = vehicle_query.filter(state=Vehicle.STATE_ACTIVE)
        inactive_vehicles = vehicle_query.filter(state=Vehicle.STATE_INACTIVE)
        return render(request, 'planner/vehicle_details.html', {
            'vehicles': {
                'active' : active_vehicles,
                'inactive': inactive_vehicles,
            }
        })

    return render(request, 'planner/vehicle_details.html', {'errormsg': 'User must have an operator!'})

@login_required
def create_vehicle(request):
    if request.method == 'POST':
        form = VehicleForm(request.POST)
        if form.is_valid():
            if request.user.operator:
                instance = form.save(commit=False)
                instance.operator = request.user.operator
                instance.save()
                return HttpResponseRedirect(reverse('planner:vehicle'))
            else:
                return render(request, 'planner/create_vehicle.html', {'form':form, 'errormsg': 'User must have an operator!'})
        else:
            return render(request, 'planner/create_vehicle.html', {'form':form})

    form = VehicleForm()
    return render(request, 'planner/create_vehicle.html', {'form':form})

@login_required
def update_vehicle(request, id):
    try:
        vehicle = Vehicle.objects.get(id=id)
    except Vehicle.DoesNotExist:
        raise Http404("Vehicle does not exist")
    if request.method == "POST":
        form = VehicleForm(request.POST ,instance=vehicle)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('planner:vehicle'))
        return render(request, 'planner/create_vehicle.html', {'form':form})

    form = VehicleForm(instance=vehicle)
    return render(request, 'planner/create_vehicle.html', {'form':form})


@login_required
def flightplan(request):
    if not request.user.operator:
        return render(request, 'planner/flightplan_details.html', {'errormsg': 'User must have an operator!'})
    operator_plans = FlightPlan.objects.filter(operator=request.user.operator)

    planned_flightplan = operator_plans.filter(Q(state=FlightPlan.STATE_PLANNED) | Q(state= FlightPlan.STATE_COMPLETED)).order_by('-planned_departure_time')
    invalid_flightplan = operator_plans.filter(state=FlightPlan.STATE_INVALID).order_by('-planned_departure_time')

    return render(request, 'planner/flightplan_details.html', {
        'flightplans' : planned_flightplan,
        'invalid_flightplan' : invalid_flightplan,
    })

def _get_flight_plan_form(form, params = {}):
    base = {
        'form':form,
        'upload_url_endpoint': reverse('planner:get_upload_url'),
        'upload_done_endpoint': reverse('planner:set_upload_complete')
    }
    return dict(base.items() + params.items())

def _update_flight_plan(request, fp=None):
    form = FlightPlanForm(request.user, request.POST, instance=fp)
    if form.is_valid():
        if not request.user.operator:
            return render(request,
                'planner/create_flight_plan.html',
                _get_flight_plan_form(form, {'errormsg': 'User must have an operator!'})
            )
        instance = form.save(commit=False)
        instance.operator = request.user.operator
        try:
            wm = WaypointMetadata.objects.get(id=form.cleaned_data['wm_id'])
        except WaypointMetadata.DoesNotExist:
            wm = None
        if wm is not None and wm.operator != request.user.operator:
            return render(request,
                'planner/create_flight_plan.html',
                _get_flight_plan_form(form, {'errormsg': 'Only waypoints you own can be used with your flight plan!'})
            )
        instance.waypoints = wm
        instance.save()
        if wm is not None:
            wm.flight_plan = instance
            wm.save()
        return HttpResponseRedirect(reverse('planner:flightplan'))
    else:
        return render(request, 'planner/create_flight_plan.html', _get_flight_plan_form(form))

@login_required
def create_flight_plan(request):
    if request.method == 'POST':
        return _update_flight_plan(request)
    form = FlightPlanForm(request.user)
    return render(request, 'planner/create_flight_plan.html', _get_flight_plan_form(form))

@login_required
def update_flight_plan(request, id):
    try:
        flightplan = FlightPlan.objects.get(id=id)
    except FlightPlan.DoesNotExist:
        raise Http404("Flight plan does not exist")
    if request.method == "POST":
        return _update_flight_plan(request, flightplan)
    form = FlightPlanForm(request.user, instance=flightplan)
    return render(request, 'planner/create_flight_plan.html', _get_flight_plan_form(form))


@login_required
def invalidate_flight_plan(request, id):
    flightplan = FlightPlan.objects.get(pk=id)
    if flightplan:
        flightplan.state = FlightPlan.STATE_INVALID
        flightplan.save()
    return HttpResponseRedirect(reverse('planner:flightplan'))

@csrf_exempt
def detail_flight_plan(request, id):
    try:
        fp = FlightPlan.objects.get(pk=id)
    except FlightPlan.DoesNotExist:
        raise Http404("Flight plan does not exist")
    waypoints = []
    if fp.waypoints is not None:
        waypoints = list(
            fp.waypoints.waypoints.all().order_by('order')
                .annotate(altitude_m=Cast(F('altitude')/100.0, FloatField()))
                .annotate(altitude_relative_m=Cast(F('altitude_relative')/100.0, FloatField()))
                .values('latitude', 'longitude', 'altitude_m', 'altitude_relative_m')
        )
    return render(request, 'planner/detail_flight_plan.html', {
        'flightplan': fp,
        'waypoints': waypoints,
        'upload_url_endpoint': reverse('planner:get_upload_url'),
        'upload_done_endpoint': reverse('planner:set_upload_complete')
    })

@login_required()
def get_upload_url(request):
    id = request.GET['id'] or None
    type = request.GET['type'] or None
    path = None
    if type == 'waypoints':
        path = document_path(request.user.operator, request.GET['filename'])
    elif type == 'telemetry':
        flightplan = FlightPlan.objects.get(pk=id)
        path = document_path(flightplan, request.GET.get('filename'))
    if path:
        return JsonResponse(data={
            "upload_url": default_storage.bucket.blob(path['path']).create_resumable_upload_session(
                size=int(request.GET['size']),
                origin="%s://%s" % (request.scheme, request.get_host())),
            "timestamp": path['timestamp']
        })
    return JsonResponse({"error": "Unknown type or id specified."}, status=404)

@login_required()
def set_upload_complete(request):
    id = request.GET['id'] or None
    try:
        fp = FlightPlan.objects.get(pk=id)
    except FlightPlan.DoesNotExist:
        # on new flight plans, forms provide a temporary invalid ID
        fp = None
    type = request.GET['type'] or None
    path = None
    if type == 'waypoints':
        path = document_path(
            request.user.operator,
            request.GET['filename'],
            timestamp=request.GET.get("timestamp")
        )
        wm = WaypointMetadata.objects.create(
            operator = request.user.operator,
            path = path['path'],
            flight_plan = fp
        )
        process_waypoints.delay(wm.id)
        return JsonResponse({
            "success": True,
            "wm_id": wm.id,
            "url": reverse('planner:get_upload_state', kwargs={'type':'waypoints', 'id':wm.id})
        }, status=200)
    elif type == 'telemetry':
        path = document_path(
            fp,
            request.GET.get('filename'),
            timestamp=request.GET.get("timestamp")
        )
        tm = TelemetryMetadata.objects.create(
            flight_plan=fp,
            path=path['path'],
            state=TelemetryMetadata.STATE_UPLOADED
        )
        process_telemetry.delay(fp.id, tm.id)
        return JsonResponse({
            "success": True,
            "tm_id": tm.id,
            "url": reverse('planner:get_upload_state', kwargs={'type':'telemetry', 'id':tm.id})
        }, status=200)
    if path is None or default_storage.exists(path['path']) is False:

templates/planner/edit_profile.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load custom_tag %}

{% block page_level_css %}
  <link href="{% static 'planner/css/profile.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
 <div class="container">
        <div class="row">
          <div class="col-md-4 col-sm-4 col-xs-12 text-center">
            <div class="side-bar">
              <img src="{% static 'planner/image/member.jpg' %}" alt="member" class="img-circle">
              <h3>{{form.instance.first_name}}</h3>
              <h5>{{form.instance.operator.organization}}</h5>
                <ul class="account">
                  <li>
                    <a href="javascript:void(0);"><i class="fa fa-home"></i>Overview</a>
                  </li>
                  <li class="active">
                    <a href="javascript:void(0);"><i class="fa fa-cog"></i>Account Settings</a>
                  </li>
                  <li>
                    <a href="javascript:void(0);"><i class="fa fa-info-circle"></i>Help</a>
                  </li> 
                </ul>
            </div>  
          </div>
          <div class="col-md-8 col-sm-8 col-xs-12">
            <div class="profile_account">
              <div class="profile_head">
                <h6>PROFILE ACCOUNT</h6>
                <ul class="nav nav-tabs navbar-right" role="tablist">
                  <li role="presentation" class="{% tabname 'personal_info' tab %}">
                    <a href="#personal_info" aria-controls="personal_info" role="tab" data-toggle="tab">Personal Info</a>
                  </li>
                  <li role="presentation" class="{% tabname 'change_pass' tab %}">
                    <a href="#change_pass" aria-controls="change_pass" role="tab" data-toggle="tab">Change Password</a>
                  </li>
                </ul>
              </div>

              <div class="tab-content">
                <div role="tabpanel" class="tab-pane {% tabname 'personal_info' tab %}" id="personal_info"> 
                  <form class="signup" id="signup_form" method="post" action="{% url 'planner:edit_profile' %}">
                    {% csrf_token %}
                    
                    <div class="form-group">
                      <label>First Name</label>
                      <input type="text" name="first_name"  class="form-control" value="{{request.user.first_name}}" required="" >
                      {{form.first_name.errors}}
                    </div>
                    <div class="form-group">
                      <label>Last Name</label>
                      <input name="last_name" type="text" class="form-control" value="{{request.user.last_name}}" required="" >
                      {{form.last_name.errors}}
                    </div>
                    <div class="form-group">
                      <label>Email</label>
                      <input type="text" name="email"  class="form-control" value="{{request.user.email}}" required="" >
                      {{form.email.errors}}
                    </div>
                    <div class="form-group">
                      <label>Mobile Number</label>
                      <input name="mobile_number" maxlength="15" type="text" class="form-control" value="{{request.user.operator.mobile_number}}" required="" >
                      {{form.mobile_number.errors}}
                    </div>
                    <div class="form-group">
                      <label>Organization</label>
                      <input type="text" name="organization" maxlength="100" class="form-control"  value="{{request.user.operator.organization}}" required="" >
                      {{form.organization.errors}}
                    </div>
                    <div class="form-group">
                      <button class="btn green-btn">Save Changes</button>
                    </div>
                  </form>
                </div>

                <div role="tabpanel" class="tab-pane {% tabname 'change_pass' tab %}" id="change_pass">
                  <form class="signup" id="signup_form" method="post" action="{% url 'planner:change_password' %}">
                    {% csrf_token %}
                    
                    <div class="form-group">
                      <label>Current Password</label>
                      <input type="password" class="form-control" name="oldpassword">
                      {{form.oldpassword.errors}}
                    </div>
                    <div class="form-group">
                      <label>New Password</label>
                      <input type="password" class="form-control" name="password1">
                      {{form.password1.errors}}
                    </div>
                    <div class="form-group">
                      <label>Re-type New Password</label>
                      <input type="password" class="form-control" name="password2">
                    </div>
                    <div class="form-group">
                      <button class="btn green-btn">Change Password</button>
                    </div>
                  </form>
                </div>

              </div>
            </div> 
          </div>
        </div>
      </div>
}
      

{% endblock %}



{% block js_block %}
{% endblock %}

templates/planner/flightplan_details.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load widget_tweaks %}

  {% block page_level_css %}
  {% endblock %}

  {% block content %}

  <div class="container">
    <h2>Flight Plans</h2>
    {% if errormsg %}
      <div class="alert alert-danger alert-dismissable">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">×</a>
        <strong> {{ errormsg }} </strong>
      </div>
    {% endif %}
    <div class="datatable-container">
      <ul class="nav nav-pills">
        <li class="active">
          <a  href="#tab-active" data-toggle="tab">Active</a>
        </li>
        <li><a href="#tab-invalidated" data-toggle="tab">Invalidated</a>
        </li>
      </ul>
      <div class="tab-content clearfix">
        <div class="tab-pane active" id="tab-active">
          <div class="table-responsive">
            <table id="flightplan-details" class="table table-striped table-bordered" width="100%" cellspacing="0">
              <thead>
                <tr>
                  <th>Flight ID</th>
                  <th>State</th>
                  <th>Departure time</th>
                  <th>Arrival time</th>
                  <th>Payload weight</th>
                  <th>Vehicle</th>
                  <th>Actions</th>
                </tr>
              </thead>
              <tbody>
                {% for flightplans in flightplans %}
                  <tr>
                    <td><a href="{% url 'planner:detail_flight_plan' flightplans.id %}">{{ flightplans.flight_id }}</a></td>
                    <td>{{ flightplans.state|title }}</td>
                    <td data-order="{{ flightplans.planned_departure_time|date:"U" }}">{{ flightplans.planned_departure_time }}</td>
                    <td data-order="{{ flightplans.planned_arrival_time|date:"U" }}">{{ flightplans.planned_arrival_time }}</td>
                    <td>{{ flightplans.payload_weight }}</td>
                    <td>{{ flightplans.vehicle.serial_number }}</td>
                    <td>
                      <a href="{% url 'planner:detail_flight_plan' flightplans.id %}" class="btn btn-xs btn-default">Details</a>
                      <a href="{% url 'planner:update_flight_plan' flightplans.id %}" class="btn btn-xs btn-default">Update</a>
                      <a href="{% url 'planner:invalidate_flight_plan' flightplans.id %}" class="btn btn-xs btn-warning">Invalidate</a>
                    </td>
                  </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
        <div class="tab-pane" id="tab-invalidated">
          <div class="table-responsive">
            <table id="invalid-flightplan" class="table table-striped table-bordered" width="100%" cellspacing="0">
              <thead>
                <tr>
                  <th>Flight ID</th>
                  <th>State</th>
                  <th>Departure time</th>
                  <th>Arrival time</th>
                  <th>Payload weight</th>
                  <th>Vehicle</th>
                  <th>Actions</th>
                </tr>
              </thead>
              <tbody>
                {% for flightplans in invalid_flightplan %}
                  <tr>
                    <td><a href="{% url 'planner:detail_flight_plan' flightplans.id %}">{{ flightplans.flight_id }}</a></td>
                    <td>{{ flightplans.state|title }}</td>
                    <td data-order="{{ flightplans.planned_departure_time|date:"U" }}">{{ flightplans.planned_departure_time }}</td>
                    <td data-order="{{ flightplans.planned_arrival_time|date:"U" }}">{{ flightplans.planned_arrival_time }}</td>
                    <td>{{ flightplans.payload_weight }}</td>
                    <td>{{ flightplans.vehicle.serial_number }}</td>
                    <td>
                      <a href="{% url 'planner:detail_flight_plan' flightplans.id %}" class="btn btn-xs btn-default">Details</a>
                      <a href="{% url 'planner:update_flight_plan' flightplans.id %}" class="btn btn-xs btn-default">Update</a>
                    </td>
                  </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>

  </div>
  {% endblock %}

  {% block js_block %}
  {% endblock %}

templates/planner/vehicle_details.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load custom_tag %}
{% load widget_tweaks %}

  {% block page_level_css %}
  {% endblock %}

  {% block content %}
    <div class="container">
      <h2>Vehicle List</h2>
      {% if errormsg %}
        <div class="alert alert-danger alert-dismissable">
          <a href="#" class="close" data-dismiss="alert" aria-label="close">×</a>
          <strong> {{ errormsg }} </strong>
        </div>
      {% endif %}
        <div class="datatable-container">
            <ul class="nav nav-pills">
                <li class="active">
                    <a href="#tab-active" data-toggle="tab">Active</a>
                </li>
                <li><a href="#tab-inactive"
                       data-toggle="tab">Inactive</a>
                </li>
            </ul>
            <div class="tab-content clearfix">
                {% for label, vehicle_list in vehicles.items %}
                <div class="tab-pane {% if label == "active"%}active{% endif %}" id="tab-{{ label }}">
                    <div class="table-responsive">
                        <table id="{{ label }}-vehicles"
                               class="table table-striped table-bordered"
                               width="100%" cellspacing="0">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>Manufacturer</th>
                                <th>Model</th>
                                <th>Serial number</th>
                                <th>Type</th>
                                <th>Empty weight</th>
                                <th>Operator</th>
                                <th>Actions</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for vehicle in vehicle_list %}
                                <tr>
                                    <td>{{ vehicle_list|length|add:1|subtract:forloop.counter }}</td>
                                    <td>{{ vehicle.manufacturer.name }}</td>
                                    <td>{{ vehicle.model }}</td>
                                    <td>{{ vehicle.serial_number }}</td>
                                    <td>{{ vehicle.vehicle_type }}</td>
                                    <td>{{ vehicle.empty_weight }}</td>
                                    <td>{{ vehicle.operator.organization }}</td>
                                    <td>
                                        <a href="{% url "planner:update_vehicle" id=vehicle.id %}" class="btn btn-xs btn-default">Update</a>
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>

    </div>
  {% endblock %}

  {% block js_block %}
  {% endblock %}