logflights/urls.py
from django.urls import include, path, re_path
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings
from django.views.generic import TemplateView
from planner import views, api_views, external_urls
from rest_framework_jwt.views import obtain_jwt_token
from rest_framework_swagger.views import get_swagger_view

urlpatterns = [
    # App routes
    path('accounts/', include('allauth.urls')),

    path('auth/api-token-auth/', obtain_jwt_token),

    # api docs
    path('api/docs', api_views.schema_view),
    re_path(r'_/docs/?', get_swagger_view(title='log.flights API')),

    # Administrative routes to be protected by http proxy / load balancer
    re_path(r'_/admin/?', admin.site.urls),
    re_path(r'_/health_check/?', views.HealthCheckView.as_view(), name='health_check'),
    path('api/internal/', include('planner.api_urls', namespace='planner_api')),
    path('api/experimental/', include('planner.external_urls', namespace='export_api')),
    path('', TemplateView.as_view(template_name='react/index.html'), name="welcome"),
    # match all other routes
    re_path(r'^(?:.*)/?$', TemplateView.as_view(template_name='react/index.html'), name="welcome"),

    # old ui

    # url(r'^$', views.welcome, name='welcome'),
    # url(r'^planner/', include('planner.urls', namespace='planner')),
    # url(r'^accounts/', include('allauth.urls')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

planner/urls.py
from django.conf.urls import url

from . import views

app_name = 'planner'

urlpatterns = [
    url(r'^vehicle/$', views.vehicle, name="vehicle"),
    url(r'^create-vehicle/$', views.create_vehicle, name="create_vehicle"),
    url(r'^update-vehicle/(?P<id>[0-9a-z]+)/$', views.update_vehicle, name="update_vehicle"),
    url(r'^terms/$', views.terms, name="terms"),

    url(r'^flightplan/$', views.flightplan, name="flightplan"),
    url(r'^create-flight-plan/$', views.create_flight_plan, name="create_flight_plan"),
    url(r'^update-flight-plan/(?P<id>[0-9a-z]+)/$', views.update_flight_plan, name="update_flight_plan"),
    url(r'^invalidate-flight-plan/(?P<id>[0-9a-z]+)/$', views.invalidate_flight_plan, name="invalidate_flight_plan"),
    url(r'^detail-flight-plan/(?P<id>[0-9a-z]+)/$', views.detail_flight_plan, name="detail_flight_plan"),

    url(r'^get-upload-url$', views.get_upload_url, name="get_upload_url"),
    url(r'^set-upload-complete$', views.set_upload_complete, name="set_upload_complete"),
    url(r'^get-upload-state/(?P<type>[a-z]+)/(?P<id>[0-9a-z]+)$', views.get_upload_state, name="get_upload_state"),
    url(r'^flightplans/(?P<id>[0-9a-z]+)/telemetry/$', views.download_telemetry, name="download_telemetry"),
    url(r'^get-flight-plan-data/(?P<id>[0-9a-z]+)/$', views.get_flight_plan_data, name="get_flight_plan_data"),
    url(r'^search-flights/$', views.search_flights, name= "search_flights"),
    url(r'^profile/$', views.edit_profile, name="edit_profile"),
    url(r'^change-password/$', views.change_password, name="change_password"),
]

templates/base.html
{% load i18n %}
{% load static %}
<!DOCTYPE html>
<html>
  {% load custom_tag %}
  {% get_env as env_value %}
  {% get_strings as strings %}
  <!-- Begin head -->
  <head>
    <title>{{ strings.PRODUCT_NAME }}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.15/css/dataTables.bootstrap.min.css">
    <link href="{% static 'planner/css/style.css' %}" rel="stylesheet">
    <link href="{% static 'planner/css/profile.css' %}" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/0.5.0/sweet-alert.css"/>

    {% block meta_block %}
    {% endblock%}
    {% block page_level_css %}
    {% endblock %}
  </head>
  <!-- End head -->
  <!-- Begin body -->
  <body>
    <!-- Begin header -->
    <header id="header">
      <!-- Begin nav -->
      <div class="container">
        <div class="row">
          <div class="col-sm-10 col-sm-10 col-xs-12">
            <h1 class=""><a href="/">{{ strings.PRODUCT_NAME }} </a></h1>
          </div>
          <div class="col-sm-2 col-sm-2 col-xs-12"></div>
        </div>
      </div>
      <nav class="navbar">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#main_menu" aria-expanded="false">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
          </div>

          <div class="collapse navbar-collapse" id="main_menu">
            <ul class="nav navbar-nav menubar">

              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Vehicle <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><a href="{% url 'planner:vehicle' %}">Vehicle List</a></li>
                  <li><a href="{% url 'planner:create_vehicle' %}">Add Vehicle</a></li>
                </ul>
              </li>

              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Flight Plan <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><a href="{% url 'planner:flightplan' %}">Flight Plan List</a></li>
                  <li><a href="{% url 'planner:create_flight_plan' %}">Add Flight Plan</a></li>
                </ul>
              </li>

              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Settings <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><a href="{% url 'planner:edit_profile' %}">Profile</a></li>
                </ul>
              </li>

            </ul>

            <div class="navbar-form navbar-right">
              {% if user.is_authenticated %}
                <a href="{% url 'account_logout'%}" class="btn btn-default"> Logout</a>
              {% else %}
                <a href="{% url 'account_login'%}" class="btn btn-default"> Login</a>
                <a href="{% url 'account_signup'%}" class="btn btn-default"> Signup</a>
              {% endif %}
            </div>

          </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
      </nav>

      <!-- END nav -->
    </header>
    <!-- END header -->
    <div class="content">
      {% block content %} {% endblock %}
    </div>

    <!-- Begin footer -->
    <footer id="footer">
      <div class="container">
        <div class="row">
          <div class="col-md-4 col-sm-4 col-xs-12">
            <p class="white">
              {{ strings.PRODUCT_NAME }} from Altiscope<br/>
              &copy; A³ by Airbus <br/>
            </p>
          </div>
          <div class="col-md-8 col-sm-8 col-xs-12">
            <p class="pull-right">
              <a class="gray" href="{% url 'terms-of-service' %}">Terms of Service</a>
              <br/>
              <a class="gray" href="{% url 'privacy-policy' %}">Privacy Policy</a>
              <br/>
              <a class="gray" target = "_blank" href="https://github.com/altiscope/logflights">github.com/altiscope/logflights</a>
            </p>
          </div>
        </div>
      </div>
    </footer>
    <!-- END footer -->

    <script src="https://cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.15/js/dataTables.bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/0.5.0/sweet-alert.min.js"></script>
    <script src="{% static 'planner/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'planner/js/planner.js' %}"></script>

    {% block js_block %}
    {% endblock %}

  </body>
  <!-- END body -->
</html>